stages:
  - build
  - deploy

variables:
  INDEX_FILE: index.txt

.common: &common
  tags: [ "runner:main", "size:large" ]

build:
  <<: *common
  stage: build
  script:
    - "true"

copy_to_s3:
  <<: *common
  stage: deploy
  image: ruby@sha256:32f9fe6d424f6f76eb88c0542dafe672ce68aec27da5ddff73bdf11a309fa773
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
    - when: manual
      allow_failure: true
  script:
    - export AWS_ACCESS_KEY_ID_REL=$(aws ssm get-parameter --region us-east-1 --name ci.dd-trace-ruby.secret_key_id --with-decryption --query "Parameter.Value" --out text)
    - export AWS_SECRET_ACCESS_KEY_REL=$(aws ssm get-parameter --region us-east-1 --name ci.dd-trace-ruby.secret_sec_key_id --with-decryption --query "Parameter.Value" --out text)
    - echo $CI_COMMIT_REF_NAME >> $INDEX_FILE
    - echo $CI_COMMIT_SHA >> $INDEX_FILE
    - echo $GITLAB_USER_NAME >> $INDEX_FILE
    - aws s3 cp $INDEX_FILE s3://datadog-reliability-env/ruby/$INDEX_FILE
