name: Test unstable
on: [push]
jobs:
  test-head:
    strategy:
      fail-fast: false
      matrix:
        ruby: [truffleruby-head]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@0c7e9c4d53d534e2c72b5b06535a3817d6d39fe1 # v1.78.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        continue-on-error: true
      - run: bundle exec rake spec:main
        continue-on-error: true
      - run: bundle exec rake spec:contrib
        continue-on-error: true
      - run: bundle exec rake spec:opentracer
        continue-on-error: true
      # A few contrib jobs that `ddtrace` already includes their gem in the global Gemfile.
      # We technically don't need appraisal to run them, thus are easy candidates for early testing.
      - run: bundle exec rake spec:rake
        continue-on-error: true
      - run: bundle exec rake spec:rspec
        continue-on-error: true
      - run: bundle exec rake spec:concurrent_ruby
        continue-on-error: true
      - run: bundle exec rake spec:http
        continue-on-error: true
